# OBSOLETE: Docker Compose Version - specifies format and available features.
# version: '3.8'

#! docker-compose automatically loads environment variables from .env files

## ==== NETWORKS ============================================================ ##
## Defines the custom networks to be created and used by the services.
networks:
  haram-leotta-network:
    # IP Address Management settings: default driver, subnet in CIDR format.
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16


## ==== SERVICES ============================================================ ##
## Defines the services (containers) that make up the application.
## Service names ar arbitrary and used for automatic container name generation.
## Service names are used for DNS resolution inside the Docker private network.
services:

  # ==== MONGO =============================================================== #
  haram-leotta-mongo:

    # Custom container name, image to be used and environment variables.
    container_name: haram-leotta-mongo
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: haram-leotta

    # Custom network settings - use haram-leotta network with static address.
    networks:
      haram-leotta-network:
        ipv4_address: 172.20.0.3

    # Bind Database data to local target directory
    # If the database has yet to be initialized, use the init script to set up users and collections
    volumes:
      - ./volumes/mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    #! TEST ONLY - Map ports between host and container - allow external access.
    ports:
      - "27017:27017"

  # ==== NODE ================================================================ #
  greve-bot-node:

    # Custom container name and environment variables.
    container_name: greve-bot-node
    environment:
      # MongoDB configuration
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: haram-leotta
      MONGO_HOST: haram-leotta-mongo
      MONGO_PORT: 27017
      # Node & Discord configuration
      NODE_ENV: dev
      LOG_LEVEL: INFO
      VERSION: 1.0.0
      TOKEN: ${TOKEN}
      PREFIX: g
      EMBED_COLOR: 0xad1457
      MUSIC_MAX_HISTORY: 5
      REDDIT_MAX_SUBS: 5

    # Build image from Dockerfile in the current directory and override its CMD.
    build: .
    command: npm run start
    image: greve-bot:latest

    # Node depends on mongo; ensure it starts before Node.
    depends_on:
      - haram-leotta-mongo

    # Custom network settings - use haram-leotta network; no need for a static address.
    networks:
      - haram-leotta-network