### SONG
GET https://api-partner.spotify.com/pathfinder/v1/query?operationName=getTrack&variables={"uri":"spotify:track:5hI0i5yUPF5fV9FhqtWbjJ"}&extensions={"persistedQuery":{"version":1,"sha256Hash":"ae85b52abb74d20a4c331d4143d4772c95f34757bfa8c625474b912b9055b5c0"}}
authorization: Bearer BQDvGh9fH1iPepzINMW9tPYKK70NPqwBoU7v6lJuvHcQBbqnVOx-145s5aTEEmyI10rakOz7gsgcTZJDRTwNfrNSGBJh_Uu0NqRCiE9E5vPxdCkr_pQ
### ALBUM
GET https://api-partner.spotify.com/pathfinder/v1/query?operationName=getAlbum&variables={"uri":"spotify:album:3IuxHkC9II53tjmZCIRwsL","locale":"","offset":0,"limit":500}&extensions={"persistedQuery":{"version":1,"sha256Hash":"0b8f7f117d97694e0a2b3ce210ba17102f4a4ee7fcfbcd4caaac815b940ac5ef"}}
authorization: Bearer BQC2l_x_UULidQSYeuTlVsShNv3hn9HWETCkQy7_GbzaTaJzcQ37-xFyblpYlDjepj7xtX_nMa4xygdHgMQls_EWWJA1HCu7vFUqIvI-syJTwrst-DY
### PLAYLIST
GET https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables={"uri":"spotify:playlist:6MHETysuXPmzK22rykYa41","offset":0,"limit":500}&extensions={"persistedQuery":{"version":1,"sha256Hash":"9086f110a0571ad24df2e16191f4efa31740df7bc11a2ee8b336f5d3a52e2bd8"}}
authorization: Bearer BQA-sIh52DiYtkTzhN0fcb6DmAiZTPPfnExcax7YlQFutyL9b1D95xtixzbTcp530RfBsG4GTz8owwBpujeTnCOwjY4AorphZKa4PWUSbFa4eiOCUK0


### YOUTUBE MIX
POST https://www.youtube.com/youtubei/v1/next?prettyPrint=false

{
  "context": {
    "client": {
      "visitorData": "CgtTQk9yX0o4SnFoTSiV84e3BjIiCgJJVBIcEhgSFhMLFBUWFwwYGRobHB0eHw4PIBAREiEgLg%3D%3D",
      "clientName": "WEB",
      "clientVersion": "2.20240910.03.00",
    }
  },
  "videoId": "W0IlDdWq7pA",
  "playlistId": "RDaJQ5HsXlPTo"
}
###
{
  "context": {
    "client": {
      "clientName": "WEB",
      "clientVersion": "2.20240910.03.00"
    }
  },
  "videoId": "KLCdoyUxUwI",
  "playlistId": "RDaJQ5HsXlPTo",
  "params": "OAE%3D",
  "playlistIndex": 24,
  "autonavState": "STATE_NONE"
}
###
GET https://www.youtube.com/watch?v=aJQ5HsXlPTo&list=RDaJQ5HsXlPTo&index=25